# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/Hans.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  inputs:
        versionSpec: '4.9.1'

# Restore Nuget Packages
- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

# Build Solution Files
- task: VSBuild@1
  displayName: '.Net Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
# Unit Testing
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    projects: '**\*Test.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage" --filter TestCategory!="LocalDependent"'

# Build NuGet Packages
- task: DotNetCoreCLI@2
  displayName: 'Nuget Pack'
  inputs:
    allowPackageConflicts: true
    command: pack
    configuration: '$(BuildConfiguration)'
    packagesToPack: 'Hans\**\*.csproj;!**\*Test.csproj'
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '$(Build.BuildNumber)'

# Publish NuGet Packages
- task: DotNetCoreCLI@2
  displayName: 'NuGet Push'
  inputs:
    command: push
    nuGetFeedType: internal
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'Hans-Nuget'
